import Foundation

/// Game phase a tier belongs to. Drives atlas grouping and board theming.
public enum GamePhase: String, Codable, Sendable {
    case earth
    case cosmic
}

/// Definition of a character tier, mirrored 1:1 from `tiers.json` (build bible §2.1).
///
/// Entries are generated by `Tools/generate-tiers` from `economy.json` — numeric
/// fields must never be edited by hand (the anti-drift test enforces this).
public struct CharacterType: Codable, Sendable, Equatable, Identifiable {
    /// Stable identifier used across board state, saves, prompts and the asset manifest.
    public let id: String
    /// Tier number, 1 (El Fisura) through 30 (Dios).
    public let tier: Int
    public let phase: GamePhase
    /// Player-facing name (rioplatense flavor lives here, not in code).
    public let displayName: String
    /// Placeholder sprite reference, e.g. `sf:person.fill` (SF Symbol) until real art ships.
    public let spritePlaceholder: String
    /// Key into `assets_manifest.json` once real art exists; `nil` renders the placeholder.
    public let spriteAssetKey: String?
    public let tapYield: Double
    public let passiveYieldPerInstance: Double
    public let passiveUnlockCost: Double
    /// Identifier of the type produced by merging two of this type; `nil` only for the
    /// terminal tier (god) and for abstract choice nodes.
    public let mergesInto: String?
    /// `true` for the abstract career-choice node (tier 9 `junior`); never placed on the board.
    public let isChoiceNode: Bool
    /// Concrete same-tier types the player picks from when a merge hits a choice node.
    public let choiceOptions: [String]?

    public init(
        id: String,
        tier: Int,
        phase: GamePhase,
        displayName: String,
        spritePlaceholder: String,
        spriteAssetKey: String?,
        tapYield: Double,
        passiveYieldPerInstance: Double,
        passiveUnlockCost: Double,
        mergesInto: String?,
        isChoiceNode: Bool,
        choiceOptions: [String]?
    ) {
        self.id = id
        self.tier = tier
        self.phase = phase
        self.displayName = displayName
        self.spritePlaceholder = spritePlaceholder
        self.spriteAssetKey = spriteAssetKey
        self.tapYield = tapYield
        self.passiveYieldPerInstance = passiveYieldPerInstance
        self.passiveUnlockCost = passiveUnlockCost
        self.mergesInto = mergesInto
        self.isChoiceNode = isChoiceNode
        self.choiceOptions = choiceOptions
    }
}

/// Top-level structure of `tiers.json`.
public struct TiersFile: Codable, Sendable {
    public let schemaVersion: Int
    public let types: [CharacterType]

    public init(schemaVersion: Int, types: [CharacterType]) {
        self.schemaVersion = schemaVersion
        self.types = types
    }
}
